<?php
/**
 * BasicOperationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Dam
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Dam Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Dam\Test\Api;

use \GeminiCommerce\Dam\Configuration;
use \GeminiCommerce\Dam\ApiException;
use \GeminiCommerce\Dam\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BasicOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Dam
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BasicOperationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for batchUploadAssets
     *
     * Batch Upload Assets.
     *
     */
    public function testBatchUploadAssets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchUploadAssets_0
     *
     * Batch Upload Assets.
     *
     */
    public function testBatchUploadAssets0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAsset
     *
     * Create Asset.
     *
     */
    public function testCreateAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAsset_0
     *
     * Create Asset.
     *
     */
    public function testCreateAsset0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAssetByCode
     *
     * Get Asset By Code.
     *
     */
    public function testGetAssetByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAssetByCode_0
     *
     * Get Asset By Code.
     *
     */
    public function testGetAssetByCode0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssets
     *
     * List Assets.
     *
     */
    public function testListAssets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssetsByCodes
     *
     * List Assets By Codes.
     *
     */
    public function testListAssetsByCodes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssetsByCodes_0
     *
     * List Assets By Codes.
     *
     */
    public function testListAssetsByCodes0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssetsByIds
     *
     * List Assets By Ids.
     *
     */
    public function testListAssetsByIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssetsByIds_0
     *
     * List Assets By Ids.
     *
     */
    public function testListAssetsByIds0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssets_0
     *
     * List Assets.
     *
     */
    public function testListAssets0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAsset
     *
     * Update Asset.
     *
     */
    public function testUpdateAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAsset_0
     *
     * Update Asset.
     *
     */
    public function testUpdateAsset0()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
